name: Bug
description: Report a problem
title: "[Bug] "
body:
  - type: textarea
    id: behavior
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Remove private IP addresses, usernames, and credentials from logs.
